name: Build and Deploy Java Spring Application to Railway

on:
  push:
    branches:
      - main  # Деплой будет запускаться при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Устанавливаем JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Используйте нужную версию JDK

      # Устанавливаем зависимости с помощью Maven
      - name: Set up Maven
        uses: actions/setup-maven@v3

      # Сборка проекта с Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Собираем проект, пропуская тесты, если не нужно их запускать

      # Деплой на Railway
      - name: Deploy to Railway
        run: |
          curl -sSL https://railway.app/nix/install.sh | sh  # Установка Railway CLI
          railway up  # Деплой на Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Токен для доступа к Railway
