name: Build and Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Java (если используете Java)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Сборка проекта с Maven
      - name: Build with Maven
        run: mvn clean package

      # Сборка Docker образа (если нужно)
      - name: Build Docker image
        run: docker build -t my-app .

      # Деплой на Railway
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
